name: Enforce PR labels

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - synchronize

jobs:
  enforce-label:
    name: Labels check (major, minor or patch)
    runs-on: ubuntu-latest
    steps:
      - name: Fail if there is no correct label
        if: |
          !contains(github.event.pull_request.labels.*.name, 'major')
          && !contains(github.event.pull_request.labels.*.name, 'minor')
          && !contains(github.event.pull_request.labels.*.name, 'patch')
        run: |
          echo "::group::Correct label NOT found"
          echo "::endgroup::"
          exit 1
